import { BestDealImage1, BestDealImage2, BestDealImage3, BestDealImage4, BestDealImage5 } from "./media";

export const bestSelling = [
  {
    id: 2,
    title: "TOZO T6 True Wireless Earbuds Bluetooth Headphon...",
    oldPrice: null,
    price: 70,
    currency: "N",
    image: BestDealImage2,
    rating: 5,
    ratingCount: 235,
    tags: ["HOT"],
    isSoldOut: false,
  },
  {
    id: 3,
    title: "Samsung Electronics Samsung Galexy S21 5G",
    oldPrice: null,
    price: 2320,
    currency: "N",
    image: BestDealImage3,
    rating: 5,
    ratingCount: 455,
    tags: ["BEST SALE"],
    isSoldOut: false,
  },
  {
    id: 4,
    title: "Amazon Basics High-Speed HDMI Cable (18 Gbps, 4K/6...",
    oldPrice: 865,
    price: 150,
    currency: "N",
    image: BestDealImage4,
    rating: 4,
    ratingCount: 124,
    tags: ["19% OFF"],
    isSoldOut: false,
  },
  {
    id: 5,
    title: "Portable Wshing Machine, 11lbs capacity Model 18NMF...",
    oldPrice: null,
    price: 1200,
    currency: "N",
    image: BestDealImage3,
    rating: 4,
    ratingCount: 345,
    tags: [],
    isSoldOut: false,
  },
  {
    id: 6,
    title: "In-House flower pot for interior decoration",
    oldPrice: null,
    price: 299,
    currency: "N",
    image: BestDealImage1,
    rating: 5,
    ratingCount: 123,
    tags: [],
    isSoldOut: false,
  },
  {
    id: 7,
    title: "Portable Washing Machine, 11lbs capacity Model 18NMF1AM",
    oldPrice: 865.99,
    price: 70,
    currency: "N",
    image: BestDealImage4,
    rating: 4,
    ratingCount: 237,
    tags: [],
    isSoldOut: false,
  },
  {
    id: 8,
    title: "Amazing lip cream for summer",
    oldPrice: null,
    price: 160,
    currency: "N",
    image: BestDealImage2,
    rating: 3,
    ratingCount: 451,
    tags: ["HOT"],
    isSoldOut: false,
  },
  {
    id: 9,
    title: "JBL FLIP 4 - Coffe preparing gadgets",
    oldPrice: 360,
    price: 250,
    currency: "N",
    image: BestDealImage5,
    rating: 5,
    ratingCount: 9643,
    tags: ["32% OFF"],
    isSoldOut: false,
  },
];
