import { BestDealImage3, BestDealImage4, BestDealImage5 } from "./media";

export const bestDeals = [
  {
    id: 2,
    title: "The super trousers for men and women - it's unisex",
    oldPrice: null,
    price: 2300,
    currency: "N",
    image: BestDealImage5,
    rating: null,
    ratingCount: null,
    tags: ["SOLD OUT"],
    isSoldOut: true,
  },
  {
    id: 3,
    title: "Ice Bottle for evening Refreshment",
    oldPrice: null,
    price: 220,
    currency: "N",
    image: BestDealImage3,
    rating: null,
    ratingCount: null,
    tags: [],
    isSoldOut: false,
  },
  {
    id: 4,
    title: "Super woman gift for valentine",
    oldPrice: 865,
    price: 150,
    currency: "N",
    image: BestDealImage4,
    rating: null,
    ratingCount: null,
    tags: ["19% OFF"],
    isSoldOut: false,
  },
  {
    id: 5,
    title: "Make Up Kit for Girls",
    oldPrice: null,
    price: 1200,
    currency: "N",
    image: BestDealImage3,
    rating: null,
    ratingCount: null,
    tags: [],
    isSoldOut: false,
  },
  {
    id: 6,
    title: "In-House flower pot for interior decoration",
    oldPrice: null,
    price: 299,
    currency: "N",
    image: BestDealImage3,
    rating: null,
    ratingCount: null,
    tags: [],
    isSoldOut: false,
  },
  {
    id: 7,
    title: "Portable Washing Machine, 11lbs capacity Model 18NMF1AM",
    oldPrice: 865.99,
    price: 70,
    currency: "N",
    image: BestDealImage4,
    rating: null,
    ratingCount: null,
    tags: [],
    isSoldOut: false,
  },
  {
    id: 8,
    title: "Amazing lip cream for summer",
    oldPrice: null,
    price: 160,
    currency: "N",
    image: BestDealImage5,
    rating: null,
    ratingCount: null,
    tags: ["HOT"],
    isSoldOut: false,
  },
  {
    id: 9,
    title: "JBL FLIP 4 - Coffe preparing gadgets",
    oldPrice: 360,
    price: 250,
    currency: "N",
    image: BestDealImage5,
    rating: null,
    ratingCount: null,
    tags: ["32% OFF"],
    isSoldOut: false,
  },
];
